#!/bin/bash

GF_INSTALL_PLUGINS="grafana-clock-panel,grafana-simple-json-datasource"
GRAFANA_VERSION="latest"

docker build --build-arg "GRAFANA_VERSION=$GRAFANA_VERSION" --build-arg "GF_INSTALL_PLUGINS=$GF_INSTALL_PLUGINS" -f $DOCKERFILE_PATH -t $IMAGE_NAME .
